# conda list -e | grep -E "bioconductor-deseq2|bioconductor-ihw|bioconductor-mygene|bioconductor-tximport|r-ggplot2|r-rcolorbrewer|r-knitr|r-rmarkdown|salmon|snakemake-minimal|r-sm|r-reshape2|r-dplyr|r-venndiagram|r-webgestaltr"
# conda env update --file conf/conda.yml  --prune
# conda env remove --name musLingon
# conda env create -f conf/conda.yml

name: musLingon

channels:
  - bioconda
  - conda-forge

dependencies:
  - bioconductor-deseq2=1.26.0
  - bioconductor-ihw=1.14.0
  - bioconductor-mygene=1.22.0
  - bioconductor-tximport=1.14.0
  - r-dplyr=1.0.1
  - r-ggplot2=3.3.2
  - r-knitr=1.29
  - r-rcolorbrewer=1.1_2
  - r-reshape2=1.4.3
  - r-rmarkdown=2.3
  - r-sm=2.2_5.6
  - r-venndiagram=1.6.20
  - r-webgestaltr=0.4.4
  - salmon=1.4.0
  - snakemake-minimal
