---
title: "Mouse Lingon diet experiment"
author:
   name: "Shuyi Li & Dmytro Kryvokhyzha"
   email: dmytro.kryvokhyzha@med.lu.se
   affiliation: LUDC Bioinformatics Unit
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
    html_document:
      keep_md: true
      toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## PI

Name: [Karin Stenkula](https://www.ludc.lu.se/karin-stenkula-assistant-professor-pi) & Karin Berger

Email: [karin.stenkula@med.lu.se](mailto:karin.stenkula@med.lu.se)

## Project

Mice were fed with different diet for 4 days:

- HFD - high fat diet,
- LFD - low fat diet,
- Lingon - high fat diet with Lingon berries.

HFD vs Lingon is the most interesting comparison. LFD is a control.

RNA-seq data were collected from adipose tissue.

Each group has 5 samples.


## Data

All the data is located on the Indigo server: `/ludc/Active_Projects/Mouse_Adipocite_Lingonberry/`

## Analyses

### NBIS analysis

This project has been first analyzed by [NBIS](https://nbis.se/)

Unfortunately, there was no clear step-by-step explanation of the analyses.
We re-cover all the analysis steps and describe the analysis in [nbis](nbis).

They comapred all three groups togather in the RSEM frameworl, 
while the main question was to perform pairwise comparisons.

So, we re-analyzed the data ourselves.

### Our analysis

[ludc](ludc) - description and results of our pair-wise analysis.
